name: Daily Check-in

on:
  push:
    branches:
      - ci
      - feature/switch-to-github-actions

jobs:
  job_fetch:
    name: Get DigitalOcean API Variables
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Setup `node-fetch`
      run: npm install node-fetch --loglevel error

    - name: Fetch Variables
      run: node main.js
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Copy master_README.md
      run: cp master_README.md output/README.md
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: output/


  job_fmt:
    name: Prettify Output Files
    needs: job_fetch
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: output
    - name: Reformat Output with Terraform
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'fmt'
        tf_actions_fmt_write: true
