name: Daily Check-in

on:
  push:
    branches:
      - ci
      - feature/switch-to-github-actions

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
